### ISSUE TITLE
Use limit-files in coala

### ISSUE THREAD

**Issue by AbdealiLoKo** [coala/coala-atom#11]
Currently there is a bug of coala running wrongly when multiple sections are involved.
We need https://github.com/coala-analyzer/coala/issues/1315 to fix it.

When coala releases that version, bump up COALA_MIN_VERSION and add that option instead of `files`

**Comment by sils** [comment]
@AbdealiJK this is no longer blocked, when can you look at it?

**Comment by AbdealiLoKo** [comment]
I was planning on doing it when coala reached 0.4.1

On Wed, Feb 10, 2016 at 10:49 PM, Lasse Schuirmann <notifications@github.com
