### ISSUE TITLE
Add linter name

### ISSUE THREAD

**Issue by Arcanemagus** [coala/coala-atom#13]
If you specify a `name` property on the provider returned then Linter will decorate your messages with your name for easy identification when multiple linters are running on the same file.

**Comment by AbdealiLoKo** [comment]
@Arcanemagus Thanks ! will do

**Comment by sils** [comment]
@Arcanemagus hey, thanks for looking into this. If you have further question just drop in at https://gitter.im/coala-analyzer/coala for a chat :)
