### ISSUE TITLE
Add gif file to show usage

### ISSUE THREAD

**Issue by AbdealiLoKo** [coala/coala-atom#20]
Like https://atom.io/packages/atom-css-comb

**Comment by sils** [comment]
yeah!

**Comment by AbdealiLoKo** [comment]
@hypothesist You wanted to work on this ?

**Comment by vlad-turcanu** [comment]
If this is not taken, I'd like to work on it.

**Comment by RohanVB** [comment]
Still working on this @vlad-turcanu ? :D

**Comment by SanketDG** [comment]
@vlad-turcanu feel free to ping us if you would like to work on this again!

**Comment by ghost** [comment]
Can anyone assign me on this issue? Can't do this via coala bot

**Comment by RohanVB** [comment]
Are you sure you wanna do this @binore ? You're making good progress on a `difficulty/low` issue.
Newcomer issues are aimed at familiarising people with the coala workflow, mainly with the commits, git and the works.

**Comment by ghost** [comment]
@RohanVB someone in gitter said, that i must do difficulty/newcomer issue anyway. Besides, I do not think that this one will take much time.

**Comment by RohanVB** [comment]
> I do not think that this one will take much time.

I think thats why we save issues like this for newcomers. Due to the limited number we have open, they're meant to get people used to coala.

> someone in gitter said, that i must do difficulty/newcomer issue anyway.

Alright then :)

**Comment by RaiVaibhav** [comment]
@binore are you still working on this

**Comment by yashovardhan** [comment]
can I work on this issue?

**Comment by RaiVaibhav** [comment]
@SanketDG @meetmangukiya  please assign someone else like @yashovardhanagrawal ,if he has not done any new comer issue

**Comment by SanketDG** [comment]
@RaiVaibhav please assign the issue now using `corobo`!

@binore unassigned due to unactivity! :)

**Comment by RaiVaibhav** [comment]
@yashovardhanagrawal  assign yourself using corobo bot on gitter

**Comment by yashovardhan** [comment]
Please have to view at #75 
I have tried to solve this issue
