### ISSUE TITLE
README.md fixes needed for MarkdownBear

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-atom#29]
See https://circleci.com/gh/coala/coala-atom/42 for details

**Comment by cociorbaandrei** [comment]
Hi i would liked to be assigned to this.

**Comment by divyanshu-rawat** [comment]
Hi ! Can I work on this .

**Comment by Makman2** [comment]
@cociorbaandrei sorry for missing your post @cociorbaandrei ! If you are still interested, I would assign you.

@divyanshu-rawat: if @cociorbaandrei doesn't want to work on this issue any more, I'm assigning you, but for now he was first^^

**Comment by ghost** [comment]
@Makman2 Just to confirm... this requires modifying README.md to address the errors shown in build.  ?

**Comment by Makman2** [comment]
@divyanshu-rawat damn sorry forgot to assign you the issue... still interested?
@dracarys09 yes :+1:

**Comment by khushmeeet** [comment]
I would like to be assigned for this project.

**Comment by RohanVB** [comment]
I guess this isn't an issue with the atom repo's readme, but rather an issue with MarkdownBear/gitmate.
[this commit](https://github.com/coala/coala-atom/pull/47/commits/8148175f93c70f2e6681316415369d0b8b4dcbc5) already fixed the issue but it still seems to be apparent when someone makes a PR like [here](https://github.com/coala/coala-atom/pull/64)

**Comment by khushmeeet** [comment]
I still didn't understand what is wrong with readme.md file
Is there some problem with syntax?

**Comment by meetmangukiya** [comment]
@Khushmeet run `coala` locally and fix the markdown errors reported by `MarkdownBear`

**Comment by khushmeeet** [comment]
I think readme.md has no errors.

**Comment by RohanVB** [comment]
Closing this issue (See comment above by me).
