### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by gaocegege** [coala/coala-atom#42]
https://github.com/coala/coala-atom/compare/v0.2.0...master

Now we have some critical changes, e.g. https://github.com/coala/coala-atom/commit/36c627c348f53554730b7fecc29385f9bc734775. The minimal version in v0.2.0 is `0.4.1.dev`, and the latest version installed from pypi is `0.10.0`. These two  versions are not comparable.

```error
Please upgrade your version of coala.
Minimum version required: 0.4.1.dev
```

The error is raised every time now, I think it's time to release a new version to solve the problem.

WDYT

**Comment by sils** [comment]
I think I just did that
