### ISSUE TITLE
Update COALA_MIN_VERSION to 0.10.0

### ISSUE THREAD

**Issue by RohanVB** [coala/coala-atom#52]

**Comment by EverWinter23** [comment]
Did I solve this issue?

**Comment by EverWinter23** [comment]
I would like to be assigned to this issue.

**Comment by RohanVB** [comment]
@EverWinter23  Have you been invited to the coala org? Please type 'Hello world' on our gitter channel if you haven't, because I can't seem to assign you to the issue until you do so
