### ISSUE TITLE
Fix Lint on Fly

### ISSUE THREAD

**Issue by ghost** [coala/coala-atom#62]
As i understand, Coala Atom starts analyse after any edit event, but not after saving of current file. So, i think that it will be better to cache data and not to run new instance of coala cli (if file checksum or last change time is the same).

Or better to rewrite code as Indie Linter Provider and run analyse on custom events (not after every change).

**Comment by ghost** [comment]
Cause on my PC it starts over 100 instances of python process after editing of one line

**Comment by RohanVB** [comment]
> 100 instances of python process after editing of one line

How did you arrive at this conclusion?

>  Coala Atom starts analyse after any edit event, but not after saving of current file.

Tried it on the `bad.py` file in the repo, which only flags `LineLengthBear` after I save the file. 
Not sure if we're on the same page here. What did you use to check the instances?

> Indie Linter Provider

Is this referring to v2 http://steelbrain.me/linter/types/indie-linter-v2.html ? I think you have another issue opened for this too

**Comment by ghost** [comment]
> How did you arrive at this conclusion?

Just type one line of code, look at the created processes and enjoy.  

`provider =
 name: 'coala'
 grammarScopes: ['*']
 scope: 'file'
 lintOnFly: true`
This is config of linter provider, `lintOnFly` is true. So, event will be generated after every changes in the code => extension will execute coala. If u set false, the callback function will be called only when the file is saved, but not after opening the file. because of that, in my opinion, `lintOnFly` was set as true, but in general it would be more correct to rewrite the code as Indie Linter Provider.

> I think you have another issue opened for this too

No, my prev issue just about migrating to v2, not using Indie Linter Provider instead of Standard Linter Provider (which is used now).

**Comment by RohanVB** [comment]
Alright, I think got it. Benefit of having `Indie Linter Provider` here is analysing whatever events we set. This'll reduce the number of processes. 
The alternative solution to reducing number of processes is by having `lintOnFly` of the linter Configs param set as false. The drawback of this is that the linter won't run when we open the file. (IMO this isn't a bad idea. we could have the param set as `false`; If I recall correctly, that's the way coala-vim works).

In regards to the other issue, I think it'll save some work if we decide we want to use  [Indie Linter Provider](http://steelbrain.me/linter/types/indie-linter-v2.html) over [Standard](http://steelbrain.me/linter/types/standard-linter-v2.html)

Are there any other advantages of using Indie that can't be done with standard?

CC @sils @AbdealiJK

**Comment by ghost** [comment]
That's all i think. Main difference between Indie and Standard is the way how we send to atom-linter analysis results (using callback or api methods).
